### PR TITLE
Fix for coq/coq#10201.

### PR DESCRIPTION
**Pull request by ppedrot**
Do not merge yet.

### CODE REVIEW

**Comment by gares** [comment]
please merge now !

**Comment by Karmaki** [comment]
It seems that the tests have failed?

**Comment by ppedrot** [comment]
They ran before the merge, you should relaunch them if you're concerned.

**Comment by Karmaki** [comment]
Mmm... Still a problem (about `opam switch`). Sorry, I don't have time to investigate right now :-(

**Comment by Karmaki** [comment]
Seem ok now. Thanks

**Pull request merged**
