### PR TITLE
fixed for ocaml 4.10.0

### PR DESCRIPTION
**Pull request by Alizter**
I don't have much idea what I'm doing, but I went ahead and fixed all the errors and warnings I was getting with ocaml 4.10.0.

### CODE REVIEW

**Comment by ybertot** [comment]
I initially misread the comment of this pull request.  The objective is really to be compatible with coq 8.12, compatibility with ocaml 4.10 is anecdotal

**Comment by Karmaki** [comment]
It seems that Travis use `8.13+alpha (July 2020)` version of coq, and the compilation leads to an error (see https://travis-ci.org/github/Karmaki/coq-dpdgraph/builds/712627596).
```
File "searchdepend.mlg", line 54, characters 8-30:
Error: The constructor Case expects 5 argument(s),
       but is applied here to 4 argument(s)
```

**Comment by ybertot** [comment]
The error message shows incompatibility with coq-master of today (8.13+alpha) but does not say anything
about compatibility with coq-8.12

I just checked this pull-request against coq-8.12 and ocaml 4.10.0 on one side, and coq-8.12 and ocaml 4.07.0 on the other side.  It works in both cases.

For now, I will create a specific coq-v8.12 branch to accept these changes and prepare an opam package.

**Comment by Karmaki** [comment]
Great, thanks :+1:

**Comment by Alizter** [comment]
I asked on Zulip, future versions of coq > 8.12 will also have only 4 arguments for `Case`. It just looks like 8.13+alpha hasn't caught up to this change yet.

**Comment by ybertot** [comment]
At least for now a coq-dpdgraph version exists that is compatible with coq-8.12 (the opam description was
just merged in opam-coq-archive/released).  It uses the code of this pull request @Alizter .

**Comment by Alizter** [comment]
Thanks @ybertot! Should we close this PR?

**Comment by ybertot** [comment]
As training ground for using git, I would like to see if I could merge this on master and keep the attribution to you, at least for the few lines that are about recent warning from ocaml.

**Comment by ybertot** [comment]
But for now, I have other matters to attend.

**Comment by ybertot** [comment]
I checked again today, and coq-master still does not include Case with 4 arguments, but we still don't have compatibility with ocaml4.10.0, because the change about remove the "Pervasive" qualifier is needed for this compatibility.

**Comment by ybertot** [comment]
Thanks!

**Pull request merged**
