### PR TITLE
add meta.yml and generate boilerplate

### PR DESCRIPTION
**Pull request by palmskog**
We use the usual Coq-community [templates](https://github.com/coq-community/templates) approach to get an opam file in the repository to drive continuous integration and generate documentation from the file `meta.yml`.

### CODE REVIEW

**Comment by palmskog** [comment]
@Karmaki @ybertot with your permission I can merge this PR and set up the same boilerplate in a branch for Coq 8.14 (laying the groundwork for the 1.0.0 release in the Coq platform).

**Comment by ybertot** [comment]
As far as I am concerned, please proceed, I trust you on this.  I will need an oral meeting to check why our process was different from usual and how this can be streamlined, also I would like to check that no functionality will be lost and that the documentation as provided by the README.md file is up to date.

**Comment by Karmaki** [comment]
Looks good to me. Anyway, the `travis` part was not working anymore, and I didn't manage to repair it. 

Maybe you can take the opportunity of this MR to also change the version to 1.0 (in `configure.ac`) since everyone seems to agree about that?

**Review by Karmaki — APPROVED** [review]

**Comment by Karmaki** [comment]
Great. Thanks.

**Pull request merged**
