### PR TITLE
Fix for coq API, and simplify test for Prop

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Not sure what the travis script is supposed to be doing but it was wrongly accepting here.

**Comment by Karmaki** [comment]
The error is:

    File "searchdepend.ml4", line 58, characters 40-55:
    Error: Unbound value Univ.out_punivs

Is it supposed to be defined in `coq` `trunk` branch? (sorry, don't have time to check it myself right now).

**Comment by SkySkimmer** [comment]
A few changes to coq trunk are necessary, see coq/coq#784.

**Comment by Karmaki** [comment]
OK. So you mean it is ok if Travis is failing right now, right?

**Comment by SkySkimmer** [comment]
Yes.

**Comment by SkySkimmer** [comment]
It works here https://travis-ci.org/SkySkimmer/coq/jobs/242907535
I had to revert the makefile change, I don't know why my machine has trouble with it.

**Comment by ybertot** [comment]
As agreed with @maximedenes for Coq, we accept this pull-request now, and they will accept the
pull request https://github.com/coq/coq/pull/784 asap.  Everything should work correctly before
the end of the day.

**Comment by ybertot** [comment]
As agreed with @maximedenes, we accept this pull request in advance of their
accepting pull requestion https://github.com/coq/coq/pull/784

All should work well before the end of the day.

**Pull request merged**
