### PR TITLE
[coq] Adapt to coq/coq#6837.

### PR DESCRIPTION
**Pull request by ejgallego**
Minor fixes.

### CODE REVIEW

**Comment by Karmaki** [comment]
It seems that there is a compilation problem in this PR:
```
File "graphdepend.ml4", line 251, characters 29-61:
Error: This expression has type
         Libnames.qualid Loc.located = Loc.t option * Libnames.qualid
       but an expression was expected of type 'a CAst.t
```

**Comment by maximedenes** [comment]
The Coq PR was merged, can you merge this one? Thanks!

**Comment by Karmaki** [comment]
@maximedenes : it seems that the compilation still failing...

**Comment by ejgallego** [comment]
Let me have a look.

**Comment by ejgallego** [comment]
Oh indeed this PR is using the wrong branch; the overlay had the correct one.

**Pull request closed without merging**
