### PR TITLE
Adapt to coq/coq#15104 (reduction tactics don't insert useless casts)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ybertot** [comment]
There is no real need for a review.  The file is an output file that is only used when the test of coq-dpdgraph is run.  The modifications are only needed because symbols will change index in some table.
This PR should be merged only when coq/coq#15104 is merged.

**Review by ybertot — APPROVED** [review]
Apart from this test file, no source is modified.

If the change of Coq provokes a change of indices in some table, it is natural that this file has to be modified.  However, the changes will make no sense to a human reader, so a review is really not needed.

**Comment by palmskog** [comment]
@SkySkimmer can you please rebase this PR to include changes in #92 and see if we get red ci?

**Comment by palmskog** [comment]
@SkySkimmer the tests are now getting run (thanks!) but due to how testing is set up, all we get is [a message, not a failure](https://github.com/coq-community/coq-dpdgraph/runs/4116257342?check_suite_focus=true#step:4:635):
```
- DIFFERENCES : diff tests/graph.dpd.oracle tests/graph.dpd.log
  - To force a new execution of the test:
  -   rm tests/graph.dpd.log ; make tests/graph.dpd.ok
  - To accept the results: 
  -   cp tests/graph.dpd.log tests/graph.dpd.oracle
  - cp tests/graph2.dpd tests/graph2.dpd.log
  -    * build tests/graph2.dpd.ok
```
Since I never worked with the test suite, maybe @ybertot can give some hints on how we can make this raise actual errors that will give a red CI.

**Comment by SkySkimmer** [comment]
Do `make test-suite` instead of `make test`

**Comment by palmskog** [comment]
@SkySkimmer easiest if you do the change in this branch so we immediately see the result, this is where you need to change `test` to `test-suite`: https://github.com/SkySkimmer/coq-dpdgraph/blob/simpl-no-pointless-cast/coq-dpdgraph.opam#L21

**Pull request closed without merging**
