### PR TITLE
Port to coqpp.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Who is maintaining this repo? @ybertot? Also, CI failure is unrelated to this patch, it is because the OCaml version used is out of date w.r.t. master.

**Comment by Karmaki** [comment]
Sorry, I have been very busy lately... Do you have some time to have a look @ybertot? Otherwise, I do it later in the week. Sorry again.

**Comment by ybertot** [comment]
@ppedrot : I only understand half of your message.  I am available for a phone conversation for clarification.

**Comment by ppedrot** [comment]
coqpp is a self-contained replacement for the Coq custom camlp5 macros. Its syntax is slightly different from the one of the camlp5 macro, so it requires minute changes to port the code. The differences are documented in https://github.com/coq/coq/blob/master/dev/doc/changes.md. We're planning to remove or at least deprecate the camlp5 macro in 8.10, so developments tracked by the Coq CI need to be ported ASAP.

**Comment by ybertot** [comment]
The part that I did not understand was about ocaml outdated version.  It should be fixed on the travis side.

**Comment by ppedrot** [comment]
OK, so this PR should be fine then.

**Comment by ybertot** [comment]
thanks

**Comment by Karmaki** [comment]
Thanks to both of you!

**Pull request merged**
