### PR TITLE
Introduce a configure file + compute also dependencies that come from the type

### PR DESCRIPTION
**Pull request by ybertot**
Il y a encore un petit problème avec le calcul de dépendance des fichiers ml4, qui n'est pas bien fait.

Sinon, la modification dans searchdepend.ml4 doit permettre d'assurer que le type des constantes est aussi utilisé pour calculer les dépendances, même pour des axiomes.

### CODE REVIEW

**Comment by Karmaki** [comment]
Merci bien ! Je testerai et fusionnerai ça dès que possible.

**Comment by Karmaki** [comment]
There is a problem with the new configuration system:

    OCamlfind detected and enabled
    checking ocamlgraph package...
      checking for /home/anne/opam/root/4.02.1/lib/ocaml/ocamlgraph/graph.cmxa... no
    configure: error: ocamlgraph is not installed.

On my machine, it is installed here:

    /home/anne/opam/root/4.02.1/lib/ocamlgraph/graph.cmxa

Is it working for you ?
OCamlfind is not used here ?

**Comment by ybertot** [comment]
No, ocamlfind is not used here.  To use ocamlfind, I would need to add a check for its presence in the configure file, which was not the case yet.  I expected ocamlgraph to be installed inside the ocaml library.  You example shows that opam installs it on the side.

The wrong lines in configure.in are lines 159-162:

AC_CHECK_FILE($OCAMLLIB/ocamlgraph/graph.cmxa,
  OCAMLGRAPH=yes,
  OCAMLGRAPH=no)

instead of calling ocamlfind.  But I have yet to understand what ocamlfind does, really.

**Comment by Karmaki** [comment]
It seems that the presence of ``ocamlfind`` is checked in the configure file. That is why I thought that you used it.

**Comment by ybertot** [comment]
On 09/28/2015 04:57 PM, Karmaki wrote:
>
> It seems that the presence of |ocamlfind| is checked in the configure 
> file. That is why I thought that you used it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Karmaki/coq-dpdgraph/pull/1#issuecomment-143767142>.
>
Okay, I'll fix it.  It may be better to reject this pull request until I 
have a more satisfactory version.  Thank you for the feedback.

Yves

**Comment by Karmaki** [comment]
It seems that the location of can be found with ``ocamlfind query ocamlgraph``

**Comment by Karmaki** [comment]
OK. Tell me when you want me to check again.
Thanks for you work anyway.

**Comment by SimonBoulier** [comment]
Hi. Is is supposed to compile?

After many attempts I got the autoconf succeding (I installed ocamlfind and ocamlgraph with opam, I did `autoconf`, and then `./configure`).

But when I launch `make` it fails with:
  `File "searchdepend.ml4", line 15, characters 11-32:`
   `Error: Unbound module Libnames.Refmap`
   `Make_coq:244: recipe for target 'searchdepend.cmx' failed`

Thank you.

**Comment by Karmaki** [comment]
It seems that coq API has changed... I'll try to have a look at that soon, but don't have the time right now.

**Comment by ybertot** [comment]
I am working on it.

**Comment by Karmaki** [comment]
OK Yves. Thanks.

**Comment by ybertot** [comment]
Dear Anne,

I just discovered that this pull-request is still premature, because I have not checked all the
commands that were provided.

**Comment by ybertot** [comment]
I think that now the code behaves pretty much as explained in the documentation (especially the colors
are now better respected).  The only thing that remains to be done is to decide what archive locations we really want to advertise.

With my best,

Yves

**Pull request merged**
