### PR TITLE
Move the travis script into the makefile

### PR DESCRIPTION
**Pull request by JasonGross**
This way, we can also run it on Coq's CI

### CODE REVIEW

**Comment by JasonGross** [comment]
What's up with these changes?
```
diff tests/graph.dpd.oracle tests/graph.dpd.log
1079,1082c1079,1081
< E: 176 177 [weight=1, ];
< E: 176 178 [weight=1, ];
< E: 176 179 [weight=1, ];
< E: 176 180 [weight=4, ];
---
> E: 176 178 [weight=2, ];
> E: 176 179 [weight=2, ];
> E: 176 180 [weight=10, ];
diff tests/graph2.dpd.oracle tests/graph2.dpd.log
14d13
< N: 202 "list_rect" [body=yes, kind=cnst, prop=no, path="Test", ];
18c17
< N: 204 "Permutation_ind" [body=yes, kind=cnst, prop=yes, path="Test", ];
---
> N: 202 "Permutation_ind" [body=yes, kind=cnst, prop=yes, path="Test", ];
22,23c21
< N: 203 "perm_nil" [kind=construct, prop=yes, path="Test", ];
< N: 201 "eq_rect" [body=yes, kind=cnst, prop=no, ];
---
> N: 201 "perm_nil" [kind=construct, prop=yes, path="Test", ];
45,46c43,44
< E: 182 203 [weight=1, ];
< E: 182 204 [weight=1, ];
---
> E: 182 201 [weight=1, ];
> E: 182 202 [weight=1, ];
64,70c62,66
< E: 185 203 [weight=1, ];
< E: 186 192 [weight=4, ];
< E: 186 195 [weight=1, ];
< E: 186 196 [weight=1, ];
< E: 186 202 [weight=1, ];
< E: 187 199 [weight=1, ];
< E: 187 201 [weight=1, ];
---
> E: 185 201 [weight=1, ];
> E: 186 192 [weight=10, ];
> E: 186 195 [weight=2, ];
> E: 186 196 [weight=2, ];
> E: 187 199 [weight=4, ];
93,103c89,95
< E: 201 199 [weight=4, ];
< E: 202 192 [weight=10, ];
< E: 202 195 [weight=2, ];
< E: 202 196 [weight=2, ];
< E: 203 192 [weight=6, ];
< E: 203 195 [weight=2, ];
< E: 203 196 [weight=6, ];
< E: 204 191 [weight=14, ];
< E: 204 192 [weight=30, ];
< E: 204 195 [weight=4, ];
< E: 204 196 [weight=12, ];
---
> E: 201 192 [weight=6, ];
> E: 201 195 [weight=2, ];
> E: 201 196 [weight=6, ];
> E: 202 191 [weight=14, ];
> E: 202 192 [weight=30, ];
> E: 202 195 [weight=4, ];
> E: 202 196 [weight=12, ];
diff tests/graph.dot.oracle tests/graph.dot.log
404c404,406
<   Test_list_ind -> Test_list_rect [] ;
---
>   Test_list_ind -> Test_cons [] ;
>   Test_list_ind -> Test_nil [] ;
>   Test_list_ind -> Test_list [] ;
diff tests/graph2.dot.oracle tests/graph2.dot.log
24,25d23
< _eq_rect [label="eq_rect", URL=<.html#eq_rect>, fillcolor="#F070D1"] ;
< Test_list_rect [label="list_rect", URL=<Test.html#list_rect>, fillcolor="#F070D1"] ;
50,51c48,51
<   Test_list_ind -> Test_list_rect [] ;
<   _eq_ind -> _eq_rect [] ;
---
>   Test_list_ind -> Test_list [] ;
>   Test_list_ind -> Test_nil [] ;
>   Test_list_ind -> Test_cons [] ;
>   _eq_ind -> _eq [] ;
72,75d71
<   _eq_rect -> _eq [] ;
<   Test_list_rect -> Test_list [] ;
<   Test_list_rect -> Test_nil [] ;
<   Test_list_rect -> Test_cons [] ;
81c77
< Test_Permutation_ind; Test_perm_nil; Test_list_rect; Test_perm_trans; Test_cons; Test_nil; Test_perm_swap; Test_perm_skip; Test_list; Test_Permutation; Test_app; Test_Permutation_trans; Test_list_ind; Test_Permutation_refl; Test_app_comm_cons; Test_app_nil_end; Test_Permutation_sym; Test_Permutation_app_swap; };
---
> Test_Permutation_ind; Test_perm_nil; Test_perm_trans; Test_cons; Test_nil; Test_perm_swap; Test_perm_skip; Test_list; Test_Permutation; Test_app; Test_Permutation_trans; Test_list_ind; Test_Permutation_refl; Test_app_comm_cons; Test_app_nil_end; Test_Permutation_sym; Test_Permutation_app_swap; };
```

**Comment by ybertot** [comment]
At first glance, it looks like a change provoked by a new presentation of equality, where eq_ind used to
depend on eq_rect, but does not anymore.  As a result, some nodes of the graph have disappeared so that index numbers change.

A textual comparison of a flattened version of the graph is very brittle.  A change in results does not necessarily mean a break.  The test suite was initially designed to raise an alarm, but I always expected it to raise many false alarm, so did @karmaki.  This is the reason our test report contains indications to help adapt the test suite to an ever-changing context.  I don't know if running this test-suite in travis is relevant.  Maybe a more abstract test, or a Coq sample that does not rely on the standard library would be more relevant.

**Comment by Karmaki** [comment]
I agree that it would be a lot better to have a Coq sample that does not rely on the standard library, but it has to be large enough to include many different constructions. I don't have time to build it myself, but if you have one, I would be happy to accept it as a substitute to the existing test. In the meanwhile, you can accept the new results as oracle to make the test pass.

**Comment by maximedenes** [comment]
Any update on this PR?

**Comment by Karmaki** [comment]
Hello Maxime :-)
Sorry. Last time I looked the tests didn't pass. But seems it is ok now. I'll have a look right now.

**Pull request merged**
