### PR TITLE
[coq] Adapt to coq/coq#6837. Superseedes #39

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
This should replace #39 and hopefully be correct.

**Comment by ejgallego** [comment]
Well, is it Travis pulling the right Coq version? I am not sure the current `.travis` script is correct wrt the cache as it doesn't do `opam update`.

**Comment by ejgallego** [comment]
I've just confirmed this branch compiles correctly in my machine.

**Comment by ejgallego** [comment]
For a quick check, I suggest you delete the Travis cache and rerun the job.

**Comment by ejgallego** [comment]
Thanks!

**Comment by Karmaki** [comment]
Thanks to you!

**Pull request merged**
