### PR TITLE
removes three deprecation messages by switching to type Names.GlobRef.t

### PR DESCRIPTION
**Pull request by ybertot**

### CODE REVIEW

**Comment by Karmaki** [comment]
Thanks Yves, but it seems that there is a problem with Travis tests...

**Comment by Karmaki** [comment]
Well, shouldn't this pull request rather be on the coq-trunk branch?

**Comment by ybertot** [comment]
I misunderstood the meaning of branches, again.

**Comment by ybertot** [comment]
Okay, the test passed, but the pull request is not to the right branch, I will redo it.  Thanks for spotting my mistake.

**Pull request closed without merging**
